name: artifact

on: [push]

env:
  ARTIFACT_NAME: my-artifact

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
  
    - name: Upload artifact for linux
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .

    
